-- CREATE SCHEMA [audit]
GO

/****** Object:  Table [audit].[DTS_LOGS]    Script Date: 4/23/2022 8:55:22 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
--DROP TABLE [audit].[DTS_LOGS]

CREATE TABLE [audit].[DTS_LOGS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[PACKAGE_LOG_ID] [uniqueidentifier] NULL,
	[PACKAGE_NAME] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TASK_NAME] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PROCEDURE_NAME] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ERROR_CODE] [bigint] NULL,
	[ERROR_MSG] [varchar](5000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PACKAGE_DURATION] [int] NULL,
	[CONTAINER_DURATION] [int] NULL,
	[ERROR_DATE] [datetime] NULL,
 CONSTRAINT [PK_ErrorLog] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = OFF) 
) 

ALTER TABLE [audit].[DTS_LOGS] ADD  CONSTRAINT [DF_ErrorLog_ErrorDate]  DEFAULT (getdate()) FOR [ERROR_DATE]
GO


